# Data Collection and Initial Exploration

This notebook focuses on loading, inspecting and understanding the datasets used in this project. The goal is to identify key features, data types and potential issues such as missing values

In [2]:
import pandas as pd
import numpy as np

In [61]:
sales = pd.read_csv("C:/Users/George/Desktop/data/Video Game Sales 2024.csv")
metacritic_games = pd.read_csv("C:/Users/George/Desktop/data/Metacritic's Best Games 2025.csv")
metacritic_reviews = pd.read_csv("C:/Users/George/Desktop/data/Metacritic's Best Reviews 2025.csv")
steam = pd.read_csv("C:/Users/George/Desktop/data/Steam Games Dataset March 2025(Cleaned).csv")

## Dataset Overview

Three datasets are used in this project (The metacritic dataset is split into 2 and will later be combined using a common column such as game title.)

## Video Game Sales Dataset Exploration

In [64]:
sales.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [65]:
sales.shape

(64016, 14)

In [66]:
sales.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='object')

In [67]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [68]:
sales.isnull().sum()

img                 0
title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

### Observations

- The dataset contains multiple columns related to game attributes such as genre, platform and publisher.
- Sales values are numerical and represent global or regional performance.
- Some columns contain missing values that need to be handled in later stages.

## Metacritic Games Dataset Exploration

In [70]:
metacritic_games.head()

,id,title,releaseDate,rating,genres,description,platforms,metascore,metascore_count,metascore_sentiment,userscore,userscore_count,userscore_sentiment,platform_metascores,developer,publisher
0,1300001290,The Legend of Zelda: Ocarina of Time,1998-11-23,E,Open-World Action,"As a young boy, Link is tricked by Ganondorf, ...",Nintendo 64,99.0,22.0,Universal acclaim,91.0,10611,Universal acclaim,99,Nintendo,"Nintendo,Gradiente"
1,1300001928,SoulCalibur,1999-09-08,T,3D Fighting,"[Xbox Live Arcade] Soulcalibur, the highest M...","Dreamcast,iOS (iPhone/iPad),Xbox 360",98.0,24.0,Universal acclaim,78.0,605,Generally favorable,"98,73,79",Namco,Namco
2,1300027043,Grand Theft Auto IV,2008-04-29,M,Open-World Action,[Metacritic's 2008 PS3 Game of the Year; Also ...,"PlayStation 3,Xbox 360,PC",98.0,86.0,Universal acclaim,83.0,4781,Generally favorable,"98,98,90",Rockstar North,"Rockstar Games,Capcom"
3,1300019237,Super Mario Galaxy,2007-11-12,E,3D Platformer,[Metacritic's 2007 Wii Game of the Year] The u...,Wii,97.0,73.0,Universal acclaim,91.0,4181,Universal acclaim,97,Nintendo,Nintendo
4,1300044129,Super Mario Galaxy 2,2010-05-23,E,3D Platformer,"Super Mario Galaxy 2, the sequel to the galaxy...",Wii,97.0,87.0,Universal acclaim,90.0,2933,Universal acclaim,97,Nintendo EAD Tokyo,"Nintendo,iQue"

In [71]:
metacritic_games.shape

(13442, 16)

In [72]:
metacritic_games.columns

Index(['id', 'title', 'releaseDate', 'rating', 'genres', 'description',
       'platforms', 'metascore', 'metascore_count', 'metascore_sentiment',
       'userscore', 'userscore_count', 'userscore_sentiment',
       'platform_metascores', 'developer', 'publisher'],
      dtype='object')

In [73]:
metacritic_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13442 entries, 0 to 13441
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   13442 non-null  int64
 1   title                13442 non-null  object
 2   releaseDate          13410 non-null  object
 3   rating               11328 non-null  object
 4   genres               13442 non-null  object
 5   description          13394 non-null  object
 6   platforms            13436 non-null  object
 7   metascore            13436 non-null  float64
 8   metascore_count      13436 non-null  float64
 9   metascore_sentiment  13436 non-null  object
 10  userscore            13442 non-null  float64
 11  userscore_count      13442 non-null  int64
 12  userscore_sentiment  11934 non-null  object
 13  platform_metascores  13436 non-null  object
 14  developer            13433 non-null  object
 15  publisher            13440 non-null  object
dtypes: float64(3), int64(2), object(11)
memory usage: 1.6+ MB

In [74]:
metacritic_games.isnull().sum()

id                        0
title                     0
releaseDate              32
rating                 2114
genres                    0
description              48
platforms                 6
metascore                 6
metascore_count           6
metascore_sentiment       6
userscore                 0
userscore_count           0
userscore_sentiment    1508
platform_metascores       6
developer                 9
publisher                 2
dtype: int64

### Observations

- This dataset includes columns related to scores.
- It can be used to analyze the relation between reviews and game success.
- There is a large ammount of missing values in the rating column.

## Metacritic Reviews Dataset Exploration

In [103]:
metacritic_reviews.head()

,id,title,quote,score,date,platform,author,publicationName,review_type
0,1300001290,The Legend of Zelda: Ocarina of Time,C’est jeu est le meilleur jeu qui ai pu existé...,100.0,2023-01-30,Nintendo 64,Filipe69,NaN,user
1,1300001290,The Legend of Zelda: Ocarina of Time,"Marcou minha infância, e realmente é um dos me...",100.0,2022-05-04,Nintendo 64,MetalLiquido,NaN,user
2,1300001290,The Legend of Zelda: Ocarina of Time,"an open world on the classic console, perhaps ...",100.0,2023-02-03,Nintendo 64,aaronnmp96,NaN,user
3,1300001290,The Legend of Zelda: Ocarina of Time,This masterpiece holds a special place in the ...,100.0,2022-10-24,Nintendo 64,AmadouIraklidis,NaN,user
4,1300001290,The Legend of Zelda: Ocarina of Time,10 out of 10 easily one of the best games of h...,100.0,2023-01-31,Nintendo 64,slushy,NaN,user

In [105]:
metacritic_reviews.shape

(1656049, 9)

In [107]:
metacritic_reviews.columns

Index(['id', 'title', 'quote', 'score', 'date', 'platform', 'author',
       'publicationName', 'review_type'],
      dtype='object')

In [109]:
metacritic_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1656049 entries, 0 to 1656048
Data columns (total 9 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   id               1656049 non-null  int64
 1   title            1656049 non-null  object
 2   quote            1655903 non-null  object
 3   score            1648853 non-null  float64
 4   date             1451941 non-null  object
 5   platform         1656049 non-null  object
 6   author           1131687 non-null  object
 7   publicationName  524357 non-null   object
 8   review_type      1656049 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 113.7+ MB

In [111]:
metacritic_reviews.isnull().sum()

id                       0
title                    0
quote                  146
score                 7196
date                204108
platform                 0
author              524362
publicationName    1131692
review_type              0
dtype: int64

### Observations

- This dataset includes user and critic ratings.
- It can be used to analyze the relation between reviews and game success.
- There are a lot of missing values in some columns but it doesn't seem they will affect the analysis.

## Steam Dataset Exploration

In [119]:
steam.head()

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
4,359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,3.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,682,2434,306,80,89916,"{'FPS': 9831, 'PvP': 9162, 'e-sports': 9072, '...",84,1168020,76,12608

In [121]:
steam.shape

(89618, 47)

In [129]:
steam.columns

Index(['appid', 'name', 'release_date', 'required_age', 'price', 'dlc_count',
       'detailed_description', 'about_the_game', 'short_description',
       'reviews', 'header_image', 'website', 'support_url', 'support_email',
       'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url',
       'achievements', 'recommendations', 'notes', 'supported_languages',
       'full_audio_languages', 'packages', 'developers', 'publishers',
       'categories', 'genres', 'screenshots', 'movies', 'user_score',
       'score_rank', 'positive', 'negative', 'estimated_owners',
       'average_playtime_forever', 'average_playtime_2weeks',
       'median_playtime_forever', 'median_playtime_2weeks', 'discount',
       'peak_ccu', 'tags', 'pct_pos_total', 'num_reviews_total',
       'pct_pos_recent', 'num_reviews_recent'],
      dtype='object')

In [131]:
steam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   appid                     89618 non-null  int64
 1   name                      89618 non-null  object
 2   release_date              89618 non-null  object
 3   required_age              89618 non-null  int64
 4   price                     89618 non-null  float64
 5   dlc_count                 89618 non-null  int64
 6   detailed_description      89421 non-null  object
 7   about_the_game            89398 non-null  object
 8   short_description         89498 non-null  object
 9   reviews                   10401 non-null  object
 10  header_image              89618 non-null  object
 11  website                   41114 non-null  object
 12  support_url               44110 non-null  object
 13  support_email             78798 non-null  object
 14  windows                   89618 non-null  bool
 15  mac                       89618 non-null  bool
 16  linux                     89618 non-null  bool
 17  metacritic_score          89618 non-null  int64
 18  metacritic_url            3547 non-null   object
 19  achievements              89618 non-null  int64
 20  recommendations           89618 non-null  int64
 21  notes                     16643 non-null  object
 22  supported_languages       89618 non-null  object
 23  full_audio_languages      89618 non-null  object
 24  packages                  89618 non-null  object
 25  developers                89618 non-null  object
 26  publishers                89618 non-null  object
 27  categories                89618 non-null  object
 28  genres                    89618 non-null  object
 29  screenshots               89618 non-null  object
 30  movies                    89618 non-null  object
 31  user_score                89618 non-null  int64
 32  score_rank                39 non-null     float64
 33  positive                  89618 non-null  int64
 34  negative                  89618 non-null  int64
 35  estimated_owners          89618 non-null  object
 36  average_playtime_forever  89618 non-null  int64
 37  average_playtime_2weeks   89618 non-null  int64
 38  median_playtime_forever   89618 non-null  int64
 39  median_playtime_2weeks    89618 non-null  int64
 40  discount                  89618 non-null  int64
 41  peak_ccu                  89618 non-null  int64
 42  tags                      89618 non-null  object
 43  pct_pos_total             89618 non-null  int64
 44  num_reviews_total         89618 non-null  int64
 45  pct_pos_recent            89618 non-null  int64
 46  num_reviews_recent        89618 non-null  int64
dtypes: bool(3), float64(2), int64(19), object(23)
memory usage: 30.3+ MB

In [133]:
steam.isnull().sum()

appid                           0
name                            0
release_date                    0
required_age                    0
price                           0
dlc_count                       0
detailed_description          197
about_the_game                220
short_description             120
reviews                     79217
header_image                    0
website                     48504
support_url                 45508
support_email               10820
windows                         0
mac                             0
linux                           0
metacritic_score                0
metacritic_url              86071
achievements                    0
recommendations                 0
notes                       72975
supported_languages             0
full_audio_languages            0
packages                        0
developers                      0
publishers                      0
categories                      0
genres                          0
screenshots                     0
movies                          0
user_score                      0
score_rank                  89579
positive                        0
negative                        0
estimated_owners                0
average_playtime_forever        0
average_playtime_2weeks         0
median_playtime_forever         0
median_playtime_2weeks          0
discount                        0
peak_ccu                        0
tags                            0
pct_pos_total                   0
num_reviews_total               0
pct_pos_recent                  0
num_reviews_recent              0
dtype: int64

### Observations

- This dataset contains information about modern PC games.
- Includes tags, categories and pricing.
- Useful for understanding player engagement and trends.